#!/bin/sh

# This hook is great for modifying files before commiting.
# This sheel script is called by 'git commit' with no arguments.

# Announce this script to the console:
echo pre-commit called

# Working directory for hook scripts is the root directory of the repository.
# Let's check that:
echo CWD:
echo $PWD

# Here we will call our scripts.
# I've choosen Python but you can run any program at this moment.

# This script will increment version number stored in github by 1.
py -m hooks.update_version

# Files that are modified during execution of this script, have to be added again.
git add data/version.pydef
